# Generated by Django 4.2.3 on 2023-08-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
