# Generated by Django 4.2.3 on 2023-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0003_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='1', upload_to='adv/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
